-- MySQL Script generated by MySQL Workbench
-- Wed Oct 23 20:53:26 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `biblioteca` ;

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `biblioteca` ;

-- -----------------------------------------------------
-- Table `biblioteca`.`autor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`autor` ;

CREATE TABLE IF NOT EXISTS `biblioteca`.`autor` (
  `idautor` INT NOT NULL AUTO_INCREMENT,
  `nombre_autor` VARCHAR(45) NOT NULL,
  `nacionalidad` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_publicacion` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idautor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `biblioteca`.`lector`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`lector` ;

CREATE TABLE IF NOT EXISTS `biblioteca`.`lector` (
  `idlector` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `estado_prestamo` VARCHAR(45) NULL DEFAULT NULL,
  `id_prestamo` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idlector`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `biblioteca`.`libro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`libro` ;

CREATE TABLE IF NOT EXISTS `biblioteca`.`libro` (
  `idlibro` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(45) NULL DEFAULT NULL,
  `id_autor` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idlibro`),
  INDEX `id_autor` (`id_autor` ASC),
  CONSTRAINT `libro_ibfk_1`
    FOREIGN KEY (`id_autor`)
    REFERENCES `biblioteca`.`autor` (`idautor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `biblioteca`.`prestamos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`prestamos` ;

CREATE TABLE IF NOT EXISTS `biblioteca`.`prestamos` (
  `idprestamos` INT NOT NULL AUTO_INCREMENT,
  `id_libros` INT NULL DEFAULT NULL,
  `id_lector` INT NULL DEFAULT NULL,
  `fecha_prest` DATE NULL DEFAULT NULL,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idprestamos`),
  INDEX `id_libros` (`id_libros` ASC),
  INDEX `id_lector` (`id_lector` ASC),
  CONSTRAINT `prestamos_ibfk_1`
    FOREIGN KEY (`id_libros`)
    REFERENCES `biblioteca`.`libro` (`idlibro`),
  CONSTRAINT `prestamos_ibfk_2`
    FOREIGN KEY (`id_lector`)
    REFERENCES `biblioteca`.`lector` (`idlector`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
